language: bash
services: docker

jobs:
  include:
    - stage: test
      before_script:
        - cd php/7.1
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.1 .
      after_script:
        - docker images

    - stage: test
      before_script:
        - cd php/7.2
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.2 .
      after_script:
        - docker images

    - stage: deploy
      script:
        - docker images
        - curl -X POST $DOCKER_HUB_TRIGGER_URL
