language: bash
services: docker

install:
  - git clone https://github.com/make-ci-great-again/docker-laravel-webpack-ci.git ~/image

before_script:
  - cd php/7.2

script:
  - travis_retry docker build -t .

after_script:
  - docker images
