language: bash
services: docker

jobs:
  include:
    - stage: test
      before_script:
        - cd php/7.1
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.1 .
      after_script:
        - docker images
        - php -v

    - stage: test
      before_script:
        - cd php/7.1/node/8
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.1-node-8 .
      after_script:
        - docker images
        - php -v
        - node -v
        - npm -v

    - stage: test
      before_script:
        - cd php/7.1/node/9
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.1-node-9 .
      after_script:
        - docker images
        - php -v
        - node -v
        - npm -v

    - stage: test
      before_script:
        - cd php/7.1/node/10
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.1-node-10 .
      after_script:
        - docker images
        - php -v
        - node -v
        - npm -v

    - stage: test
      before_script:
        - cd php/7.2
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.2 .
      after_script:
        - docker images
        - php -v

    - stage: test
      before_script:
        - cd php/7.2/node/8
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.2-node-8 .
      after_script:
        - docker images
        - php -v
        - node -v
        - npm -v

    - stage: test
      before_script:
        - cd php/7.2/node/9
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.2-node-9 .
      after_script:
        - docker images
        - php -v
        - node -v
        - npm -v

    - stage: test
      before_script:
        - cd php/7.2/node/10
      script:
        - docker build -t make-ci-great-again/docker-laravel-webpack-ci:php-7.2-node-10 .
      after_script:
        - docker images
        - php -v
        - node -v
        - npm -v

    - stage: deploy
      branches:
        only:
          - master
      script:
        - docker images
        - curl -X POST $DOCKER_HUB_TRIGGER_URL
